# Generated by Django 4.0.4 on 2022-05-28 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(verbose_name='datec')),
                ('city', models.CharField(max_length=256, verbose_name='city')),
                ('hall', models.CharField(max_length=256, verbose_name='hall')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
            ],
            options={
                'db_table': 'concert',
                'ordering': ['datec'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='title_news')),
                ('details', models.TextField(verbose_name='details_news')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo_news')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datet', models.DateTimeField(verbose_name='datet')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_concert', to='band.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['datet'],
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['daten'], name='news_daten_a29edb_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['datec'], name='concert_datec_4aa355_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['datet'], name='ticket_datet_188690_idx'),
        ),
    ]
