# Generated by Django 4.0.4 on 2023-03-27 08:51

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

import datetime

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='music260222@mail.ru',
    password='SsNn5678+-@')
    print("Суперпользователь создан")
            
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-')
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    user = User.objects.create_user(username='user1', password='Uu0066+-', first_name='Алуа', last_name = 'Днекешева', email = 'user1@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user2', password='Uu0066+-', first_name='Мариям', last_name = 'Жолдыбаева', email = 'user2@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user3', password='Uu0066+-', first_name='Ерлан', last_name = 'Калбаев', email = 'user3@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user4', password='Uu0066+-', first_name='Касымхан', last_name = 'Мукташев', email = 'user4@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user5', password='Uu0066+-', first_name='Карим', last_name = 'Искаков', email = 'user5@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user6', password='Uu0066+-', first_name='Асем', last_name = 'Курганбаева', email = 'user6@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user7', password='Uu0066+-', first_name='Дамир', last_name = 'Такенов', email = 'user7@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user8', password='Uu0066+-', first_name='Асель', last_name = 'Токенова', email = 'user8@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user9', password='Uu0066+-', first_name='Маргарита', last_name = 'Юрочкина', email = 'user9@mail.ru', last_login=datetime.datetime.now())
    user = User.objects.create_user(username='user10', password='Uu0066+-', first_name='Екатерина', last_name = 'Ким', email = 'user10@mail.ru', last_login=datetime.datetime.now())
    print("Созданы простые пользователи")

    ##### Концерты #####

    Concert = apps.get_model("band", "Concert")

    concert = Concert()
    concert.datec='2023-06-15 21:00:00'
    concert.city='г. Алматы'
    concert.hall='Great Hall, пр-т. Абая 4, Алматы 050000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-16 21:00:00'
    concert.city='г. Алматы'
    concert.hall='Great Hall, пр-т. Абая 4, Алматы 050000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-17 22:00:00'
    concert.city='г. Алматы'
    concert.hall='Great Hall, пр-т. Абая 4, Алматы 050000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-20 20:00:00'
    concert.city='г. Караганда'
    concert.hall='Дворец культуры горняков, просп. Бухар-Жырау 32, Караганда 100000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-21 20:00:00'
    concert.city='г. Караганда'
    concert.hall='Дворец культуры горняков, просп. Бухар-Жырау 32, Караганда 100000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-22 20:00:00'
    concert.city='г. Караганда'
    concert.hall='Дворец культуры горняков, просп. Бухар-Жырау 32, Караганда 100000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-24 20:00:00'
    concert.city='г. Нур-Султан'
    concert.hall='Конгресс-Центр Астана, ул. Сауран 44, Нур-Султан 020000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-25 20:00:00'
    concert.city='г. Нур-Султан'
    concert.hall='Конгресс-Центр Астана, ул. Сауран 44, Нур-Султан 020000'
    concert.price=1500
    concert.save()

    concert = Concert()
    concert.datec='2023-06-26 20:00:00'
    concert.city='г. Нур-Султан'
    concert.hall='Конгресс-Центр Астана, ул. Сауран 44, Нур-Султан 020000'
    concert.price=1500
    concert.save()

    print("Концерты добавлены")

    ##### Билеты #####
    Ticket = apps.get_model("band", "Ticket")

    ticket = Ticket()
    ticket.datet='2023-03-25 21:20:00'
    ticket.concert_id=1
    ticket.price=1500
    ticket.user_id=1
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-25 21:25:00'
    ticket.concert_id=2
    ticket.price=1500
    ticket.user_id=2
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-25 21:30:00'
    ticket.concert_id=3
    ticket.price=1500
    ticket.user_id=3
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-25 21:35:00'
    ticket.concert_id=4
    ticket.price=1500
    ticket.user_id=4
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-25 21:40:00'
    ticket.concert_id=5
    ticket.price=1500
    ticket.user_id=5
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-26 21:45:00'
    ticket.concert_id=6
    ticket.price=1500
    ticket.user_id=6
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-26 21:50:00'
    ticket.concert_id=7
    ticket.price=1500
    ticket.user_id=7
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-26 21:55:00'
    ticket.concert_id=8
    ticket.price=1500
    ticket.user_id=8
    ticket.save()

    ticket = Ticket()
    ticket.datet='2023-03-26 22:00:00'
    ticket.concert_id=9
    ticket.price=1500
    ticket.user_id=9
    ticket.save()    

    ticket = Ticket()
    ticket.datet='2023-03-26 22:05:00'
    ticket.concert_id=9
    ticket.price=1500
    ticket.user_id=10
    ticket.save()    

    print("Билеты добавлены")

    ##### Новости #####
    News = apps.get_model("band", "News")

    news = News()
    news.daten='2013-01-01 21:20:00'
    news.title='"Слово в слово". Новый трек Скриптонита обсуждают в Сети'
    news.details=""" Казахстанский рэпер Скриптонит (Адиль Жалелов) после недавнего заявления о том, что теперь слушателей ждет другая музыка, представил новый трек. Подробнее о новом фите рассказывает Tengri Lifestyle.
На своей странице в Instagram Скриптонит поделился новостью - он выпустил фит с Samurai SLT, bludkidd и Pervakova. Название композиции, которая длится чуть меньше четырех минут, - "Слово в слово".'"""
    news.photo='images/news1.jpeg'
    news.save()
    
    news = News()
    news.daten='2023-02-14 21:20:00'
    news.title='"Благодаря TikTok-хиту погасил кредиты". Мы задали неловкие вопросы Moreart'
    news.details="""Редакция Tengri Lifestyle продолжает новую рубрику - знакомство с талантливыми казахстанскими молодыми музыкантами. Следующий герой, который отвечает на пять не самых простых вопросов, - рэпер Moreart.
Настоящее имя артиста - Куат Куралбаев. Во многом он прославился благодаря треку "Я буду [наказывать]", который стал вирусным в TikTok и наделал много шума в 2021 году.
Куату тридцать три года, у него есть супруга и сын. За его плечами сложное детство в 90-х, несколько попыток получить высшее образование, работа гострайтером (он долгое время писал песни для других) и резкий взлет, благодаря тому самому хиту. """
    news.photo='images/news2.jpeg'
    news.save()
    
    news = News()
    news.daten='2023-02-25 21:20:00'
    news.title='Лейбл выпустит незаконченный альбом Дархана Джунусбекова'
    news.details="""Лейбл õzen, участником которого был казахстанский музыкант Дархан Джунусбеков (Darkhan Juzz), погибший в ДТП на мопеде в Таиланде, рассказал, что у них хранится невыпущенный альбом исполнителя, передает Tengrinews.kz.
В посте лейбла в Instagram говорится, что авторские права и деньги от продажи альбома достанутся его детям – сыну Ади и дочери Айдане. """
    news.photo='images/news3.jpeg'
    news.save()
    
    news = News()
    news.daten='2023-03-01 21:20:00'
    news.title='"Пацан с душой художника" - друзья и коллеги поделись личными воспоминаниями о Darkhan Juzz'
    news.details="""Друзья и коллеги рассказали корреспонденту Tengrinews.kz о жизни и творчестве Дархана Джунусбекова, известного как Darkhan Juzz. Они поделились неизвестными подробностями его биографии, а также рассказали, как рождались самые известные его песни.
Похороны казахстанского артиста, рэп-исполнителя и инди-музыканта Darkhan Juzz пройдут сегодня, 1 марта, в Алматы. Коллеги и знакомые Дархана рассказали, каким он был человеком в личном общении и в творчестве, а также чем музыка Darkhan Juzz запомнилась лично им.
Основатель медиа-компании õzen, которая выпускал музыку Darkhan Juzz, Айзатулла Хуссейн рассказал, что исполнитель был очень чувствительным человеком как в жизни, так и в творчестве. """
    news.photo='images/news4.jpeg'
    news.save()
    
    news = News()
    news.daten='2023-03-02 21:20:00'
    news.title='Концертное исполнение оперы Чайковского представили солисты академии Astana Opera'
    news.details="""Концертное исполнение оперы "Иоланта" Петра Чайковского с большим успехом представили солисты Международной оперной академии Astana Opera. История о целительной силе любви не оставила зрителей равнодушными: они горевали и радовались вместе с героями волшебного повествования под гениальную музыку в тонкой нюансировке дирижера-постановщика Руслана Баймурзина, которую филигранно воплотили в жизнь Симфонический оркестр и хор театра.
"Первый выпуск Международной оперной академии Astana Opera собрал одаренных и целеустремленных молодых певцов, которые с удовольствием и интересом вбирают в себя знания и бесценный опыт преподавателей, лучших в своей профессии, - отмечает заслуженный деятель Казахстана, директор "Астана Опера" Галым Ахмедьяров. – Концертная постановка оперы "Иоланта", которую талантливо исполнили ребята, – важный экзамен в их карьере, новый этап творческого совершенствования. Благодарные зрители нашего театра с особой теплотой относятся к молодым голосам, поддерживают академистов. Надеемся, в скором времени у них появятся новые возможности раскрыть свой потенциал, заслужив любовь не только столичных ценителей оперного пения, но и найдя поклонников в Казахстане, а также за рубежом". """
    news.photo='images/news5.jpeg'
    news.save()
    
    news = News()
    news.daten='2023-03-15 21:20:00'
    news.title='Казахские песни снова попали в тренды социальных сетей'
    news.details="""Казалось бы, со словами "трендовая казахская музыка" мы ассоциируем треки таких исполнительней, как Скриптонит, Jah Khalib, Назима, и других звезд отечественной эстрады. Тем не менее зарубежные слушатели прославляют хиты, которые и вовсе многие из нас слышат впервые. Подробнее рассказывает Tengri Life.
Так, два известных инфлюенсера из TikTok, один из которых делает музыку у себя дома, а второй известный певец Итай Бенда, использовали для своего творчества казахские песни."""
    news.photo='images/news6.jpeg'
    news.save()

    news = News()
    news.daten='2023-03-23 21:20:00'
    news.title='Поездка на 17 миллионов просмотров: таксист из Астаны стал звездой в соцсетях'
    news.details="""К чему вы готовы, садясь каждый раз в такси? К спорам о политике и мироустройстве или историях об успешных стартапах? Занимающийся частным извозом астанчанин Арман, или поющий таксист Арни, как он сам себя называет, ломает эти стереотипы - подробнее в материале Tengri Life.
Вот уже много лет Арман дарит своим пассажирам хорошее настроение, исполняя в дороге популярные песни. Делает это он исключительно по зову души и сердца и не только за рулем.
"Например, в кафе. Бывает, все вокруг молчат, а ты вдруг нарушаешь эту тишину и начинаешь петь. Или кассир в магазине без настроения – почему бы ей не поднять его песней? – рассказывает поющий таксист Арни. – Если какая-то конфликтная ситуация, женщина с кем-то ругается, то в последнее время я начал "применять" песню "Ты так красива, изящна, нежна и изменчива". И все, обстановка моментально разряжается"."""
    news.photo='images/news7.jpeg'
    news.save()
    
    print("Новости добавлены")
 
class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),
    ]
